### ISSUE TITLE
when will this code release?

### ISSUE THREAD

**Issue by Njasa2k** [ximinng/DiffSketcher#1]

**Comment by 201700301267** [comment]
I have the same question.

**Comment by comeeasy** [comment]
I read your paper and certainly hope to check this out soon!

**Comment by ximinng** [comment]
Thank you for your interest in our work. Regarding the code, our paper is currently under review and we expect to release it once the paper is accepted (expected in September).

Best regards,
Ximing

**Comment by TruthSearcher** [comment]
I am wondering this too, do we expect a release of code any time soon?

**Comment by zhtjtcz** [comment]
Thank you for your attention, the code has been released!
