### ISSUE TITLE
Ask about the conditions for generating final_render.png

### ISSUE THREAD

**Issue by Yhc-777** [ximinng/DiffSketcher#13]
Sorry to bother you in your busy schedule~

I wanna ask why the final_render.png is sometimes generated and sometimes not? Are there any conditions? Thanks for your kind help!

**Comment by ximinng** [comment]
hello Yhc-777,

According to the logic in pipline, when the program is finished executing, it generates `final_render.png` based on the last recorded state in DiffVG.
