### ISSUE TITLE
Color Strokes & Oil Painting

### ISSUE THREAD

**Issue by mattdesl** [ximinng/DiffSketcher#2]
Hi there, thanks for releasing all this code and the simple setup instructions.

I'm curious about the colourful and oil painting results on the [project page](https://ximinng.github.io/DiffSketcher-project/). Is it already achievable with the current state of this repo? Or are there missing features that need to be added as per the TODOs?

**Comment by ximinng** [comment]
Hello, mattdesl,

The current version can achieve oil painting and colorful results. However, we have not released the hyperparameter configuration YAML file or provided instructions to run the script. Please give us some time, as we will soon publish these resources.

Have a nice day~

**Comment by ximinng** [comment]
We have implemented all the features, including oil painting and colorful results.
