### ISSUE TITLE
The location of the stable diffusion?

### ISSUE THREAD

**Issue by hoshizhang** [ximinng/DiffSketcher#4]
Hello, as a beginner to generate vector graphics, I am very happy to read your research paper and code, in the configuration of the environment to conduct experiments, I encountered such a problem, would like to ask you where the location of the stable diffusion model should be placed?
![QQ20231020-095407](https://github.com/ximinng/DiffSketcher/assets/137846828/6819d60e-8944-4eae-82e5-e60257c2b90b)

**Comment by ximinng** [comment]
hi zhang,

Add `--download` flag to run cmd. And download stable-diffusion models from huggingface automatically when you first run them. The model will be placed in `~\.cache\`.

have a nice day
ximing
