### ISSUE TITLE
Style file

### ISSUE THREAD

**Issue by darkzbaron** [ximinng/DiffSketcher#7]
Hi thanks for this great repo! 

Can you explain what the style file does (--style_path argument) ? Is it the same as Stable DIffusion embeddings?

Any way to condition the sketch generation with an existing picture also?

**Comment by ximinng** [comment]
hello darkzbaron,

`--style_path` is used to load the style diagram. We haven't updated this part of the code yet, we are working on it.
As for the second question, I think you can simply modify the pipeline to load an existing picture as `target_img`.

Best regards,
Ximing

**Comment by darkzbaron** [comment]
Cool, will do thanks so much for this amazing model!
