### ISSUE TITLE
GPU Memory requirement

### ISSUE THREAD

**Issue by LordLiang** [ximinng/DiffSketcher#8]
Wonderful work! 
I want to know the minimum GPU  memory requirement. I only have a 2080Ti GPU and I failed to run the example with "gradient_checkpoint=True". What parameters can I change to help to reduce the GPU memory? Thanks!

**Comment by ximinng** [comment]
hello LordLiang,

This is really bad news, I think at least 15GB of GPU memory is required to run the code, mainly because of the stable-diffusion, using xformer and gradient_checkpoint can reduce the memory.

Best regards,
Ximing

**Comment by LordLiang** [comment]
> hello LordLiang,
> 
> This is really bad news, I think at least 15GB of GPU memory is required to run the code, mainly because of the stable-diffusion, using xformer and gradient_checkpoint can reduce the memory.
> 
> Best regards, Ximing

I see. Thank you again!
