### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by hoshizhang** [ximinng/DiffSketcher#9]
Hello, dear author, thank you very much for your answers to the questions I asked before. Now I have run through the code and have also learned the code. But the question remains, is this code only used to draw sketch vectors? What does the code look like when calculating the loss function against the label? I would appreciate it if you could answer this question! Best wishes!

**Comment by ximinng** [comment]
hello hoshizhang,

This code can also be used to draw vector graphs with RGB attributes on the path.
I don't understand the meaning of label in your second question. Can you explain?

Best regards,
Ximing
